_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "/opt/data/private/SA-SSL/semi-maskrcnn/240725_1/model_final.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss"
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (179990, 179995)
  MAX_ITER: 180000
  IMS_PER_BATCH_LABEL: 4
  IMS_PER_BATCH_UNLABEL: 2
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 1000
DATALOADER:
  SUP_PERCENT: 1.0
  RANDOM_DATA_SEED: 0
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("coco_organoids_train",)
  TEST: ("coco_organoids_val",)
SEMISUPNET:
  Trainer: "mask_rcnn_pteacher"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 2000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 4.0
TEST:
  EVAL_PERIOD: 1000
  EVALUATOR: "COCOeval"
  VAL_LOSS: False
